plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

android {
    compileSdk 36

    defaultConfig {
        minSdk 26
        targetSdk 36

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlin {
        jvmToolchain(21)
    }
    namespace 'com.mrmannwood.applist'
}

dependencies {
    api "androidx.annotation:annotation:$androidx_annotation"
    api "androidx.core:core-ktx:$android_core_ktx"
    api "androidx.lifecycle:lifecycle-livedata-ktx:$lifecycle_ktx"
    api "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    api "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    api "com.jakewharton.timber:timber:$timber_version"
}